### ISSUE TITLE
Support Swift 4

### ISSUE THREAD

**Issue by afelicioni** [boehlerlukas/NoMoreStorage#4]
Running on recent XCode version, having _Unsupported Swift Version warning_
<img width="280" alt="Schermata 2022-03-15 alle 10 47 57" src="https://user-images.githubusercontent.com/1416945/158351949-284ae220-760c-4138-bcd1-d6db3dc64916.png">

**Comment by boehlerlukas** [comment]
Hey @afelicioni !

I currently don't have the time to really work on this repo anymore, but I'm happy to review any PRs that would update it from Swift 3.X to 4.

**Comment by iandundas** [comment]
🪄#5
